# Generated by Django 5.2.5 on 2025-09-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruteria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruta',
            old_name='familia',
            new_name='origen',
        ),
    ]
