# Generated by Django 5.2.5 on 2025-09-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruteria', '0002_rename_familia_fruta_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='frutas',
            field=models.ManyToManyField(to='fruteria.fruta'),
        ),
    ]
