# Generated by Django 5.2.5 on 2025-09-02 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruteria', '0003_pedido_frutas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='frutas',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fruta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fruteria.fruta'),
            preserve_default=False,
        ),
    ]
