# Generated by Django 5.2.5 on 2025-09-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruteria', '0004_remove_pedido_frutas_pedido_fruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fruta',
        ),
        migrations.AddField(
            model_name='pedido',
            name='frutas',
            field=models.ManyToManyField(to='fruteria.fruta'),
        ),
    ]
